fix deadlock in reservations
jitsi/jicofo pull request #597
Opened 2020-09-26 04:19 UTC by zoftdev

In jitsi-meet with reservations system,I found deadlock in FocusExpireTask & ConferenceExpireTask.

Lock sequence:
FocusExpireTask : conferencesSyncRoot -> RESTReservations object
ConferenceExpireTask : RESTReservations object-> conferencesSyncRoot

 
The proposed code is to fix at reservations side.
ConferenceExpireTask should lock manager.conferencesSyncRoot first  to ensure no deadlock happen.

More log evident at: https://community.jitsi.org/t/deadlock-between-focusexpiretask-and-conferenceexpiretask-in-jicofo/79445

2020-09-26 04:34 UTC, zoftdev commented
already signed CLA , where I send email to?

2020-09-26 23:14 UTC, bgrozev commented
Thanks for the contribution! I confirm the CLA. Jenkins will keep asking, but you can ignore it (the integration with the CLA system is incomplete).

2020-10-20 12:52 UTC, damencho requested changes
We had updated recently some java coding styles https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-contributing

2020-10-20 12:52 UTC, damencho commented on src/main/java/org/jitsi/impl/reservation/rest/RESTReservations.java
> +            synchronized (focusManager.getLock()){ //prevent deadlock
Please, can you fix the formatting of the opening brace to be on new line?

2020-10-20 12:52 UTC, damencho commented on src/main/java/org/jitsi/impl/reservation/rest/RESTReservations.java
> +                        = conferenceMap.values().iterator();
Nit, can be on one line.

2020-10-20 12:52 UTC, damencho commented on src/main/java/org/jitsi/impl/reservation/rest/RESTReservations.java
> +                        }
Nit, maybe on same line if it does not exceeds the 120 column.

2020-10-20 12:52 UTC, damencho commented on src/main/java/org/jitsi/jicofo/FocusManager.java
> +    public final Object getLock(){
Same, opening brace.

2022-01-28 18:44 UTC, bgrozev commented
The reservation system has been removed.

2022-01-28 18:44 UTC, closed without merging